vector_from_func_calls <- function(n, return.mode="numeric", func, ...){
    #===========================================================================
    #                                                     VECTOR FROM FUNC CALLS
    #===========================================================================
    # This function allows you to generate a new vector, of size n, in which the 
    # values of the elements are automatically generated by continuously calling 
    # some function n times. 
    #
    # This differs from something like sapply by the fact that the function 
    # called is not fed the value of an exisiting vector element as an argument. 
    # The function called is fed the exact same arguments every single time. It 
    # is thus most useful when the function you are calling returns a different 
    # value each time. 
    # Moreover, you do not feed a vector as an argument here, you simply specify 
    # how big you want the vector to be. 
    # 
    # ARGS: 
    #   n           : How big you wan the vector to be.
    #   return.mode : The data type of the values in the vector
    #   func        : The function you actually want to call, that will return 
    #                 the individual values for you.
    #  ...          : The arguments you wish to pass to func
    #===========================================================================
    vec = vector(return.mode, n)
    for (i in 1:length(vec)){
        vec[i] = func(...)
    }
    return(vec)
}